Formatting

diff --git a/bin/lamassu-install b/bin/lamassu-install
--- a/bin/lamassu-install
+++ b/bin/lamassu-install
@@ -122,10 +122,10 @@ eval $upgrade >> $debug 2>&1
 echo "Creating user accounts (lamassu, operator)..."
 
 useradd -m operator
-[ $? -ne 0 ] && fail "Creating an operator user account failed"
+[ $? -ne 0 ] && fail "Creating \`operator\` user account failed"
 
 useradd -s /bin/nologin lamassu
-[ $? -ne 0 ] && fail "Creating an lamassu user account failed"
+[ $? -ne 0 ] && fail "Creating \`lamassu\` user account failed"
 
 # Install PostgreSQL with the package manager we found.
 echo "Installing PostgreSQL (this might take a while)..."
