Install `lamassu-scripts` globally

diff --git a/bin/lamassu-install b/bin/lamassu-install
--- a/bin/lamassu-install
+++ b/bin/lamassu-install
@@ -184,6 +184,10 @@ openssl req -new -newkey rsa:8092 -days 9999 -nodes -x509 -subj "/C=US/ST=/L=/O=
 
 chmod 600 /root/{*.key,*.crt}
 
+echo "Installing lamassu-scripts globally"
+$(cd "$dir" && npm install -g >> $debug 2>&1)
+[ $? -ne 0 ] && fail "Installing lamassu-scripts globally failed"
+
 echo "Starting Lamassu services..."
 start lamassu-admin >> $debug 2>&1
 [ $? -ne 0 ] && fail "Starting lamassu-admin failed"
