Rename `op` to `sysadmin`

diff --git a/bin/lamassu-install b/bin/lamassu-install
--- a/bin/lamassu-install
+++ b/bin/lamassu-install
@@ -121,18 +121,18 @@ eval $upgrade >> $debug 2>&1
 
 echo "Creating user accounts (lamassu, operator)..."
 
-useradd -g yes -m op >> $debug 2>&1
-[ $? -ne 0 ] && fail "Creating \`operator\` user account failed"
-echo 'op ALL=(ALL) NOPASSWD' >> /etc/sudoers
-[ $? -ne 0 ] && fail "Adding \`operator\` as a sudoer failed"
+useradd -g yes -m sysadmin >> $debug 2>&1
+[ $? -ne 0 ] && fail "Creating \`sysadmin\` user account failed"
+echo 'sysadmin ALL=(ALL) NOPASSWD' >> /etc/sudoers
+[ $? -ne 0 ] && fail "Adding \`sysadmin\` as a sudoer failed"
 
 useradd -s /bin/nologin lamassu >> $debug 2>&1
 [ $? -ne 0 ] && fail "Creating \`lamassu\` user account failed"
 
 echo "Setting up and securing SSH..."
-mkdir /home/op/.ssh >> $debug 2>&1
-cp /root/.ssh/authorized_keys /home/op/.ssh >> $debug 2>&1
-chown -R op:op /home/op/.ssh >> $debug 2>&1
+mkdir /home/sysadmin/.ssh >> $debug 2>&1
+cp /root/.ssh/authorized_keys /home/sysadmin/.ssh >> $debug 2>&1
+chown -R sysadmin:sysadmin /home/sysadmin/.ssh >> $debug 2>&1
 
 echo 'PermitRootLogin no' >> /etc/ssh/sshd_config
 [ $? -ne 0 ] && fail "Disallowing \`root\` SSH logins failed"
