Add `operator` to sudoers
Add `root` `authorized_keys` to `operator` user account.

Disable `root` SSH logins.

diff --git a/bin/lamassu-install b/bin/lamassu-install
--- a/bin/lamassu-install
+++ b/bin/lamassu-install
@@ -123,9 +123,19 @@ echo "Creating user accounts (lamassu, operator)..."
 
 useradd -m operator >> $debug 2>&1
 [ $? -ne 0 ] && fail "Creating \`operator\` user account failed"
+echo 'operator ALL=(ALL) NOPASSWD' >> /etc/sudoers
+[ $? -ne 0 ] && fail "Adding \`operator\` as a sudoer failed"
 
 useradd -s /bin/nologin lamassu >> $debug 2>&1
 [ $? -ne 0 ] && fail "Creating \`lamassu\` user account failed"
+
+echo "Setting up and securing SSH..."
+mkdir /home/operator/.ssh >> $debug 2>&1
+cp /root/.ssh/authorized_keys /home/operator/.ssh >> $debug 2>&1
+chown -R operator:operator /home/operator/.ssh >> $debug 2>&1
+
+echo 'PermitRootLogin no' >> /etc/ssh/sshd_config
+[ $? -ne 0 ] && fail "Disallowing \`root\` SSH logins failed"
 
 # Install PostgreSQL with the package manager we found.
 echo "Installing PostgreSQL (this might take a while)..."
